# Generated by Django 6.0.6 on 2026-06-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("aadhaar", models.CharField(max_length=12)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("student_class", models.CharField(max_length=10)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                ("fa1", models.IntegerField(default=0)),
                ("fa2", models.IntegerField(default=0)),
                ("sa1", models.IntegerField(default=0)),
                ("fa3", models.IntegerField(default=0)),
                ("fa4", models.IntegerField(default=0)),
                ("sa2", models.IntegerField(default=0)),
            ],
        ),
    ]
